# add bind to fast reload
unbind r; bind r source-file ~/.config/tmux/tmux.conf; display "reloaded ~/.config/tmux/tmux.conf"

# rebind prefix
unbind C-b
set -g prefix C-space
bind C-space send-prefix

# Ensure terminal colors and transparency work through tmux
set-option -g default-terminal "tmux-256color"
set-option -sa terminal-overrides ",xterm*:Tc"

# admit weakness
set -g mouse on

# Vi mode in copy mode (enables vim navigation with <prefix> + [)
setw -g mode-keys vi

# store more history
set-option -g history-limit 9999999

# make select-pane more vimmy 
bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R

# set base-index and pane-base-index to 1
set -g base-index 1
set -g pane-base-index 1

# auto renumber-windows
set -g renumber-windows on

# make split-window intuitive
bind "|" split-window -hc "#{pane_current_path}"
bind "\\" split-window -fhc "#{pane_current_path}"

bind "-" split-window -vc "#{pane_current_path}"
bind "_" split-window -fvc "#{pane_current_path}"

# explicitly tell tmux to pass your modifier keys (like Option or Ctrl) through to the inner shell
# https://www.reddit.com/r/tmux/comments/f7iw5o/can_shiftarrow_keys_be_enabled/
set-window-option -g xterm-keys on

# Set cursor style - blinking block for active pane
set -g cursor-style blinking-block

# https://github.com/dreamsofcode-io/tmux/blob/main/tmux.conf
set -g @catppuccin_flavour 'mocha'

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-yank'
# https://github.com/catppuccin/tmux
set -g @plugin 'catppuccin/tmux'


run '~/.config/tmux/plugins/tpm/tpm'

